blank_issues_enabled: false
contact_links:
  - name: CTAppTemplate.jl package support
    url: https://github.com/control-toolbox/CTAppTemplate.jl/discussions
    about: Please ask and answer questions about CTAppTemplate.jl here.
  - name: Control-toolbox organisation support
    url: https://github.com/orgs/control-toolbox/discussions
    about: For more general questions about control-toolbox ecosystem it's here.
